# Generated by Django 5.0.14 on 2026-03-07 13:24

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Game",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("board_state", models.JSONField(default=list)),
                ("current_turn", models.IntegerField(default=1)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("waiting", "Waiting"),
                            ("active", "Active"),
                            ("finished", "Finished"),
                            ("abandoned", "Abandoned"),
                        ],
                        db_index=True,
                        default="waiting",
                        max_length=20,
                    ),
                ),
                ("is_ranked", models.BooleanField(default=False)),
                ("is_ai_game", models.BooleanField(default=False)),
                (
                    "ai_difficulty",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("easy", "Easy"),
                            ("medium", "Medium"),
                            ("hard", "Hard"),
                        ],
                        max_length=10,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "games_game",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Move",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("from_row", models.IntegerField()),
                ("from_col", models.IntegerField()),
                ("to_row", models.IntegerField()),
                ("to_col", models.IntegerField()),
                ("captured_row", models.IntegerField(blank=True, null=True)),
                ("captured_col", models.IntegerField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "games_move",
                "ordering": ["created_at"],
            },
        ),
    ]
