# Generated by Django 5.0.14 on 2026-03-21 19:21

from django.db import migrations, models


def backfill_guest_local_2p(apps, schema_editor):
    """Guest non-AI games were always local hot-seat."""
    Game = apps.get_model("games", "Game")
    Game.objects.filter(player_one__isnull=True, is_ai_game=False).update(
        is_local_2p=True,
    )


class Migration(migrations.Migration):

    dependencies = [
        ("games", "0003_game_chat_message"),
    ]

    operations = [
        migrations.AddField(
            model_name="game",
            name="is_local_2p",
            field=models.BooleanField(default=False),
        ),
        migrations.RunPython(backfill_guest_local_2p, migrations.RunPython.noop),
    ]
