# Generated by Django 5.2.12 on 2026-03-29 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("games", "0010_matchsession_game_match_session_gamechallenge_is_match"),
    ]

    operations = [
        migrations.AlterField(
            model_name="game",
            name="time_control_sec",
            field=models.PositiveIntegerField(
                default=600,
                help_text="Seconds each player has per turn (e.g. 600 = 10 minutes); resets when turns change.",
            ),
        ),
        migrations.AlterField(
            model_name="matchsession",
            name="is_raw",
            field=models.BooleanField(
                default=False,
                help_text="True when the match ended with no mini-game wins for the loser (e.g. 5–0).",
            ),
        ),
    ]
