# Generated by Django 5.0.14 on 2026-03-24 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="facebook_id",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="Facebook app-scoped user id when linked.",
                max_length=32,
                null=True,
                unique=True,
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="tiktok_open_id",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="TikTok open_id when linked via Login Kit.",
                max_length=64,
                null=True,
                unique=True,
            ),
        ),
    ]
